Added a square root function as the _pow(0.5) was not giving correct …
InjectiveLabs/cw-injective pull request #112
Opened 2023-02-28 22:27 UTC by maxrobot

…result for 4^0.5

Also would be good to know if anyone has opinions on the root methodology?

We could add in a break for the loop on line 70 with a tolerance.

Also removed the generic CosmWasm notices from cargo generate.

2023-02-28 23:11 UTC, keithbaum approved these changes
Looks ok

2023-03-01 05:44 UTC, gorgos requested changes
`sdk.Dec` is using max 100 iterations https://github.com/cosmos/cosmos-sdk/blob/44495e7a7934f00fe289c9f059ff3dba6582b43e/math/dec.go#L423, but Im also fine with the current approach.

2023-03-01 05:44 UTC, gorgos commented on packages/injective-math/src/fp_decimal/exp.rs
> +    pub fn _root(a: FPDecimal) -> Option<FPDecimal> {
if it's a function meant for external use, you should call it `root`. And maybe `sqrt` is better?

2023-03-01 15:06 UTC, DrunkRandomWalker commented
One suggestion set `exp(0.5)` to use `sqrt`

2023-03-01 15:19 UTC, DrunkRandomWalker approved these changes
LGTM, One suggestion: set `exp(0.5)` to use `sqrt`

2023-03-01 21:41 UTC, gorgos approved these changes

2023-03-02 09:47 UTC, merged