chore: add scaling functions to fpdecimal
InjectiveLabs/cw-injective pull request #151
Opened 2023-06-20 09:41 UTC by Tofel

2023-06-20 10:22 UTC, gorgos requested changes
LGTM just one comment

2023-06-20 10:22 UTC, gorgos commented on packages/injective-math/src/fp_decimal/from_str.rs
> +        let sign = i8::from(!input.starts_with('-'));
trying this for the second time now, the old code is more readable, I know you get this suggested from somewhere, I don't though, maybe need to fix your IDE?

2023-06-20 12:34 UTC, Tofel commented on packages/injective-math/src/fp_decimal/from_str.rs
> +        let sign = i8::from(!input.starts_with('-'));
This is coming from `clippy`. What version are you using? I have `clippy 0.1.66 (69f9c33d 2022-12-12)`

2023-06-21 07:16 UTC, gorgos commented on packages/injective-math/src/fp_decimal/from_str.rs
> +        let sign = i8::from(!input.starts_with('-'));
`clippy 0.1.69 (84c898d6 2023-04-16)`

2023-06-21 07:48 UTC, gorgos approved these changes

2023-06-21 07:48 UTC, merged