F/short subaccount id change
InjectiveLabs/cw-injective pull request #159
Opened 2023-07-11 08:32 UTC by Tofel

Convert subaccount_id to decimal when creating a new instance of short subaccount id.

2023-07-11 18:15 UTC, gorgos requested changes

2023-07-11 18:15 UTC, gorgos commented on packages/injective-cosmwasm/src/exchange/types.rs
> +        // let's check first check again if it's a hexadecimal number and parse to decimal (expected by the chain)
```suggestion
        // chain expects decimal number, but ShortSubaccountId stores hexadecimal string
```

2023-07-11 18:15 UTC, gorgos commented on packages/injective-cosmwasm/src/exchange/types.rs
> +            Err(_) => Err(S::Error::custom("Invalid value: ShortSubaccountId was not a hexadecimal number")),
why not add the `self.0` to the error?

2023-07-11 18:15 UTC, gorgos commented on packages/injective-cosmwasm/src/exchange/types.rs
> +        };
I would add the `?` here.

2023-07-11 18:15 UTC, gorgos commented on packages/injective-cosmwasm/src/exchange/types.rs
> +        // if the string cannot be parsed to a decimal return error otherwise let's pad it with left zeros
unnecessary comment

2023-07-11 18:15 UTC, gorgos commented on packages/injective-cosmwasm/src/exchange/types.rs
> +        match number_to_use.parse::<u16>() {
I don't think we need this, do we? if we already do the conversion to decimal during serializations.

- If we do, please say why and remove the comments.
- If we don't, please remove here.

2023-07-12 08:40 UTC, Tofel commented on packages/injective-cosmwasm/src/exchange/types.rs
> +        match number_to_use.parse::<u16>() {
Well, I think we should validate the input, when a new instance is created. You don't want to find out that input is invalid only when you're serializing it, which would probably when submessage is dispatched? 

This part could deffo be removed here:
```
       // if it is a hexadecimal number, let's pad it with left zeros
        let number_to_use = format!("{:0>3}", decimal_u32.to_string());
```

Also, I will make that code more concise. Plus, add a method `must_new()` which will panic on invalid input. I that once this PR is merged we should change all usages of `unchecked()` for `must_new()`: https://github.com/InjectiveLabs/cw-injective/issues/160

2023-07-17 10:53 UTC, Tofel commented
@gorgos added support for deserializing from long subaccount id, added some tests and added validate function (that's now used by `new()`, `must_new()` and `serialize()` and `deserialize()`.

2023-07-17 19:12 UTC, gorgos requested changes
The changes LGTM, but I thought we discussed also adding a new feature to deserialize a long subaccount id into the short type?

2023-07-18 07:12 UTC, gorgos approved these changes

2023-07-18 09:34 UTC, merged