F/injective-math improvements
InjectiveLabs/cw-injective pull request #186
Opened 2023-10-25 16:58 UTC by DrunkenRandomWalker

1. replaced `bigint` with `primitive-types`, because `bigint` is deprecated.
2. improved `exp`, `pow`, and `ln` numerical precision to double precision.
3. added newton's method, discrete_newton's method, halley's method for root finding.

2023-10-26 16:13 UTC, DrunkenRandomWalker commented on packages/injective-math/src/fp_decimal/exp.rs
> +
we have `pow` function its in line 58

2023-10-26 16:14 UTC, DrunkenRandomWalker commented on packages/injective-math/src/lib.rs
> +pub mod root_findings;
i just pushed root finding algos

2023-10-26 16:15 UTC, DrunkenRandomWalker commented on packages/injective-math/src/fp_decimal/exp.rs
> +    // }
fixed

2023-10-26 16:23 UTC, DrunkenRandomWalker commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            num: U256::try_from(num).unwrap(),
yes, it can panic.

In `Bigint` used `U512.into()`.
https://github.com/paritytech/bigint/blob/7e71521a61b009afc94c91135353102658550d42/src/uint.rs#L1044C1-L1058C2

It can panic too. So I decided to be consistent with `Bigint`

2023-10-26 16:28 UTC, DrunkenRandomWalker commented on packages/injective-math/Cargo.toml
> +version     = "0.1.24"
I bumped version to 0.2.0

2023-10-26 22:02 UTC, DrunkenRandomWalker commented
> Seems like a good step to making the package better but can we:
> 
>     1. make sure there is a consistent interface
> 
> 
> Meaning that all public functions are not underscored, and if they are not to be public the to perform that at the function definition level
> 
> Keep mathematical operations like power, exp, sqrt available.
> 
>     2. Also remove uncommented code
> 
>     3. There is use of unwrap which I think is unsafe, please make sure we are handling unwraps appropriately.

1 and 2 are done.

2023-10-30 22:42 UTC, gorgos requested changes
looks mostly good, although I cant go through the math in detail of course, hopefully the tests and us using the new version will be sufficient

2023-10-30 22:42 UTC, gorgos commented on packages/injective-math/src/fp_decimal/log.rs
> +        if *self == FPDecimal::ZERO {
you can use`is_zero()` here

2023-10-30 22:42 UTC, gorgos commented on packages/injective-math/src/fp_decimal/log.rs
> +            // FIXME should be an undefined, not sure if it will be better to just add assert!(b>0)
I recommend returning `StdResult<FPDecimal>`

2023-10-30 22:42 UTC, gorgos commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            return FPDecimal::ZERO;
how does that make any sense?

2023-10-30 22:42 UTC, gorgos commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            num: U256::try_from(num).unwrap(),
well in the case of division it cannot happen right? except for the one edge case of: `MAX_FPDECIMAL / -1`

2023-10-31 13:22 UTC, DrunkenRandomWalker commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            return FPDecimal::ZERO;
The x and y have opposite sign in here.

2023-10-31 14:55 UTC, DrunkenRandomWalker commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            num: U256::try_from(num).unwrap(),
Yes, I think overflow can only happen in `MIN_FPDecimal/-1`. because `abs(Min) = Max +1`

2023-10-31 15:44 UTC, gorgos commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            return FPDecimal::ZERO;
So why not move the check higher above `if x.num > y.num {` ?

2023-10-31 17:10 UTC, DrunkenRandomWalker commented on packages/injective-math/src/fp_decimal/arithmetic.rs
> +            return FPDecimal::ZERO;
I thought this will save some cpu cycles

2023-11-01 22:12 UTC, gorgos approved these changes
LGTM

2023-11-02 14:21 UTC, merged